// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prog5_3C2025.Data;

#nullable disable

namespace Prog5_3C2025.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251015010401_cosa12")]
    partial class cosa12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prog5_3C2025.Models.Compras", b =>
                {
                    b.Property<int>("CPS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CPS_ID"));

                    b.Property<DateTime>("CPS_FECHA")
                        .HasColumnType("datetime2");

                    b.Property<int>("Usuario")
                        .HasColumnType("int");

                    b.HasKey("CPS_ID");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Prog5_3C2025.Models.Detalles_compras", b =>
                {
                    b.Property<int>("DRL_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DRL_ID"));

                    b.Property<int>("Compras")
                        .HasColumnType("int");

                    b.Property<int>("DRL_CANTIDAD")
                        .HasColumnType("int");

                    b.Property<float>("DRL_COSTO")
                        .HasColumnType("real");

                    b.Property<int>("Producto")
                        .HasColumnType("int");

                    b.HasKey("DRL_ID");

                    b.ToTable("Detalles_compras");
                });

            modelBuilder.Entity("Prog5_3C2025.Models.Producto", b =>
                {
                    b.Property<int>("PRD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PRD_ID"));

                    b.Property<int>("PRD_CANTIDAD")
                        .HasColumnType("int");

                    b.Property<string>("PRD_DESCRIPCION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRD_IMG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRD_NOMBRE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PRD_PRECIO")
                        .HasColumnType("real");

                    b.HasKey("PRD_ID");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Prog5_3C2025.Models.Rol", b =>
                {
                    b.Property<int>("ROL_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ROL_ID"));

                    b.Property<bool>("ROL_TIPO")
                        .HasColumnType("bit");

                    b.HasKey("ROL_ID");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Prog5_3C2025.Models.Usuario", b =>
                {
                    b.Property<int>("USR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("USR_ID"));

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("USR_MAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USR_NOMBRE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USR_PASS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("USR_ID");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
